In [1]:
import pandas as pd

# Datos de la tabla de plataformas
data = {
    "platform": ["2600", "3DO", "3DS", "DC", "DS", "GB", "GBA", "GC", "GEN", "GG", "N64", "NES", "NG", "PC"],
    "min": [1980, 1994, 2011, 1998, 1985, 1988, 2000, 2001, 1990, 1992, 1996, 1983, 1993, 1985],
    "max": [1989, 1995, 2016, 2008, 2013, 2001, 2007, 2007, 1994, 1992, 2002, 1994, 1996, 2016],
    "active_years": [9, 1, 5, 10, 28, 13, 7, 6, 4, 0, 6, 11, 3, 31],
}

df_platforms = pd.DataFrame(data)

In [2]:
df_platforms

   platform   min   max  active_years
0      2600  1980  1989             9
1       3DO  1994  1995             1
2       3DS  2011  2016             5
3        DC  1998  2008            10
4        DS  1985  2013            28
5        GB  1988  2001            13
6       GBA  2000  2007             7
7        GC  2001  2007             6
8       GEN  1990  1994             4
9        GG  1992  1992             0
10      N64  1996  2002             6
11      NES  1983  1994            11
12       NG  1993  1996             3
13       PC  1985  2016            31

In [3]:
# Ordenamos por el año de aparición para calcular la diferencia entre lanzamientos
df_platforms = df_platforms.sort_values(by="min")
df_platforms["years_between"] = df_platforms["min"].diff()

# Calculamos los promedios
avg_time_between_new_platforms = df_platforms["years_between"].mean()
avg_lifetime_platforms = df_platforms["active_years"].mean()

print(f"Tiempo promedio entre la aparición de nuevas plataformas: {avg_time_between_new_platforms:.2f} años")
print(f"Tiempo de vida promedio de las plataformas: {avg_lifetime_platforms:.2f} años")

Tiempo promedio entre la aparición de nuevas plataformas: 2.38 años
Tiempo de vida promedio de las plataformas: 9.57 años